// Code generated by Slice Machine. DO NOT EDIT.

import ComingSoon from './ComingSoon/index.svelte';
import HeroHomepage from './HeroHomepage/index.svelte';

export const components = {
	coming_soon: ComingSoon,
	hero_statement: HeroHomepage
};
