// Code generated by Slice Machine. DO NOT EDIT.

import AbstractHighlights from './AbstractHighlights/index.svelte'
import FloatingImages from './FloatingImages/index.svelte'
import StickyTitleSection from './StickyTitleSection/index.svelte'
import ComingSoon from './ComingSoon/index.svelte'
import ContactBlock from './ContactBlock/index.svelte'
import CareersHero from './CareersHero/index.svelte'
import ContentImageGrid from './ContentImageGrid/index.svelte'
import CtaProfileContact from './CtaProfileContact/index.svelte'
import FeatureGrid from './FeatureGrid/index.svelte'
import FeatureGrid2 from './FeatureGrid2/index.svelte'
import FeatureIntroDoubleColumn from './FeatureIntroDoubleColumn/index.svelte'
import FeaturedCtaBlocks from './FeaturedCtaBlocks/index.svelte'
import HeadlineWithImageTrail from './HeadlineWithImageTrail/index.svelte'
import HeroHomepage from './HeroHomepage/index.svelte'
import HeroWithBackground from './HeroWithBackground/index.svelte'
import HeroWithIntroAndColumns from './HeroWithIntroAndColumns/index.svelte'
import HeroWithOverflowingImage from './HeroWithOverflowingImage/index.svelte'
import HeroWithSplitVisual from './HeroWithSplitVisual/index.svelte'
import RevealTypeBlock from './RevealTypeBlock/index.svelte'
import ImageTextColumns from './ImageTextColumns/index.svelte'
import ImageTextBlock from './ImageTextBlock/index.svelte'
import ImageTextRevealTypeAvatar from './ImageTextRevealTypeAvatar/index.svelte'
import StickyFeatures from './StickyFeatures/index.svelte'
import HeroWithOverflowingMedia from './HeroWithOverflowingMedia/index.svelte'
import MarqueeText from './MarqueeText/index.svelte'
import FeatureCards from './FeatureCards/index.svelte'
import ServiceOverview from './ServiceOverview/index.svelte'
import StepCardList from './StepCardList/index.svelte'
import TimelineSteps from './TimelineSteps/index.svelte'
import TrustedBy from './TrustedBy/index.svelte'
import RevealTypeWithCta from './RevealTypeWithCta/index.svelte'

export const components = {
	abstract_highlights: AbstractHighlights,
	assurance_with_images: FloatingImages,
	centered_message: StickyTitleSection,
	coming_soon: ComingSoon,
	contact_block: ContactBlock,
	content_hero: CareersHero,
	content_image_grid: ContentImageGrid,
	cta_profile_contact: CtaProfileContact,
	feature_grid: FeatureGrid,
	feature_grid_2: FeatureGrid2,
	feature_intro_double_column: FeatureIntroDoubleColumn,
	featured_cta_blocks: FeaturedCtaBlocks,
	headline_with_corner_images: HeadlineWithImageTrail,
	hero_statement: HeroHomepage,
	hero_with_background: HeroWithBackground,
	hero_with_intro_and_columns: HeroWithIntroAndColumns,
	hero_with_overflowing_image: HeroWithOverflowingImage,
	hero_with_split_visual: HeroWithSplitVisual,
	highlighted_text_block: RevealTypeBlock,
	image_text_columns: ImageTextColumns,
	image_text_columns_2: ImageTextBlock,
	image_text_reveal_type_avatar: ImageTextRevealTypeAvatar,
	independent_design: StickyFeatures,
	intro_with_media_row: HeroWithOverflowingMedia,
	marquee_text: MarqueeText,
	pillars: FeatureCards,
	service_overview: ServiceOverview,
	step_card_list: StepCardList,
	timeline_steps: TimelineSteps,
	trusted_by: TrustedBy,
	value_proposition: RevealTypeWithCta
}
