// Code generated by Slice Machine. DO NOT EDIT.

import FloatingImages from './FloatingImages/index.svelte';
import ComingSoon from './ComingSoon/index.svelte';
import HeroHomepage from './HeroHomepage/index.svelte';
import StickyFeatures from './StickyFeatures/index.svelte';
import FeatureCards from './FeatureCards/index.svelte';
import TrustedBy from './TrustedBy/index.svelte';
import RevealTypeWithCta from './RevealTypeWithCta/index.svelte';

export const components = {
	assurance_with_images: FloatingImages,
	coming_soon: ComingSoon,
	hero_statement: HeroHomepage,
	independent_design: StickyFeatures,
	pillars: FeatureCards,
	trusted_by: TrustedBy,
	value_proposition: RevealTypeWithCta
};
