// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client'

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] }

type PickContentRelationshipFieldData<
	TRelationship extends
		| prismic.CustomTypeModelFetchCustomTypeLevel1
		| prismic.CustomTypeModelFetchCustomTypeLevel2
		| prismic.CustomTypeModelFetchGroupLevel1
		| prismic.CustomTypeModelFetchGroupLevel2,
	TData extends Record<
		string,
		| prismic.AnyRegularField
		| prismic.GroupField
		| prismic.NestedGroupField
		| prismic.SliceZone
	>,
	TLang extends string
> =
	// Content relationship fields
	{
		[TSubRelationship in Extract<
			TRelationship['fields'][number],
			prismic.CustomTypeModelFetchContentRelationshipLevel1
		> as TSubRelationship['id']]: ContentRelationshipFieldWithData<
			TSubRelationship['customtypes'],
			TLang
		>
	} & // Group
	{
		[TGroup in Extract<
			TRelationship['fields'][number],
			| prismic.CustomTypeModelFetchGroupLevel1
			| prismic.CustomTypeModelFetchGroupLevel2
		> as TGroup['id']]: TData[TGroup['id']] extends prismic.GroupField<
			infer TGroupData
		>
			? prismic.GroupField<
					PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
				>
			: never
	} & // Other fields
	{
		[TFieldKey in Extract<
			TRelationship['fields'][number],
			string
		>]: TFieldKey extends keyof TData ? TData[TFieldKey] : never
	}

type ContentRelationshipFieldWithData<
	TCustomType extends
		| readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
		| readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
	TLang extends string = string
> = {
	[ID in Exclude<
		TCustomType[number],
		string
	>['id']]: prismic.ContentRelationshipField<
		ID,
		TLang,
		PickContentRelationshipFieldData<
			Extract<TCustomType[number], { id: ID }>,
			Extract<prismic.Content.AllDocumentTypes, { type: ID }>['data'],
			TLang
		>
	>
}[Exclude<TCustomType[number], string>['id']]

type AdvisorySubpageDocumentDataSlicesSlice =
	| HeroWithBackgroundSlice
	| MarqueeTextSlice
	| FeatureGrid2Slice
	| FeatureGridSlice
	| FeatureIntroDoubleColumnSlice
	| ServiceOverviewSlice
	| ImageTextColumnsSlice
	| PillarsSlice
	| AssuranceWithImagesSlice
	| IndependentDesignSlice
	| TrustedBySlice
	| ValuePropositionSlice
	| HeroWithSplitVisualSlice

/**
 * Content for Advisory subpage documents
 */
interface AdvisorySubpageDocumentData {
	/**
	 * Slice Zone field in *Advisory subpage*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: advisory_subpage.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	slices: prismic.SliceZone<AdvisorySubpageDocumentDataSlicesSlice> /**
	 * Meta Title field in *Advisory subpage*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: advisory_subpage.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_title: prismic.KeyTextField

	/**
	 * Meta Description field in *Advisory subpage*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: advisory_subpage.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_description: prismic.KeyTextField

	/**
	 * Meta Image field in *Advisory subpage*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: advisory_subpage.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	meta_image: prismic.ImageField<never>
}

/**
 * Advisory subpage document from Prismic
 *
 * - **API ID**: `advisory_subpage`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AdvisorySubpageDocument<Lang extends string = string> =
	prismic.PrismicDocumentWithUID<
		Simplify<AdvisorySubpageDocumentData>,
		'advisory_subpage',
		Lang
	>

type AssuranceSubpageDocumentDataSlicesSlice = never

/**
 * Content for Assurance subpage documents
 */
interface AssuranceSubpageDocumentData {
	/**
	 * Slice Zone field in *Assurance subpage*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: assurance_subpage.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	slices: prismic.SliceZone<AssuranceSubpageDocumentDataSlicesSlice> /**
	 * Meta Title field in *Assurance subpage*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: assurance_subpage.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_title: prismic.KeyTextField

	/**
	 * Meta Description field in *Assurance subpage*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: assurance_subpage.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_description: prismic.KeyTextField

	/**
	 * Meta Image field in *Assurance subpage*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: assurance_subpage.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	meta_image: prismic.ImageField<never>
}

/**
 * Assurance subpage document from Prismic
 *
 * - **API ID**: `assurance_subpage`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AssuranceSubpageDocument<Lang extends string = string> =
	prismic.PrismicDocumentWithUID<
		Simplify<AssuranceSubpageDocumentData>,
		'assurance_subpage',
		Lang
	>

/**
 * Item in *Footer → Social icons*
 */
export interface FooterDocumentDataSocialIconsItem {
	/**
	 * Social icon field in *Footer → Social icons*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer.social_icons[].social_icon
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	social_icon: prismic.LinkField<
		string,
		string,
		unknown,
		prismic.FieldState,
		'linkedin' | 'mail' | 'instagram' | 'tiktok'
	>
}

/**
 * Item in *Footer → Columns*
 */
export interface FooterDocumentDataColumnsItem {
	/**
	 * Column title field in *Footer → Columns*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Advisory
	 * - **API ID Path**: footer.columns[].column_title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	column_title: prismic.KeyTextField

	/**
	 * Links field in *Footer → Columns*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer.columns[].links
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	links: prismic.Repeatable<
		prismic.LinkField<string, string, unknown, prismic.FieldState, never>
	>
}

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
	/**
	 * Logo field in *Footer*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer.logo
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	logo: prismic.ImageField<never>

	/**
	 * Social icons field in *Footer*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer.social_icons[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	social_icons: prismic.GroupField<Simplify<FooterDocumentDataSocialIconsItem>>

	/**
	 * CTA Link field in *Footer*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: Connect with us
	 * - **API ID Path**: footer.cta_link
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	cta_link: prismic.LinkField<
		string,
		string,
		unknown,
		prismic.FieldState,
		never
	> /**
	 * Columns field in *Footer*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer.columns[]
	 * - **Tab**: Columns
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	columns: prismic.GroupField<Simplify<FooterDocumentDataColumnsItem>>
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
	prismic.PrismicDocumentWithoutUID<
		Simplify<FooterDocumentData>,
		'footer',
		Lang
	>

/**
 * Item in *Header → Main menu items*
 */
export interface HeaderDocumentDataMenuItemsItem {
	/**
	 * Label field in *Header → Main menu items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: header.menu_items[].label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	label: prismic.KeyTextField

	/**
	 * Link field in *Header → Main menu items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: It's either a link or a sub menu, not both!
	 * - **API ID Path**: header.menu_items[].link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>

	/**
	 * Has submenu field in *Header → Main menu items*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: header.menu_items[].has_submenu
	 * - **Documentation**: https://prismic.io/docs/fields/boolean
	 */
	has_submenu: prismic.BooleanField

	/**
	 * Submenu field in *Header → Main menu items*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: header.menu_items[].submenu
	 * - **Documentation**: https://prismic.io/docs/fields/content-relationship
	 */
	submenu: ContentRelationshipFieldWithData<
		[{ id: 'sub_menu'; fields: ['submenu_item'] }]
	>
}

/**
 * Content for Header documents
 */
interface HeaderDocumentData {
	/**
	 * Logo (Light) field in *Header*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: header.logo_light
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	logo_light: prismic.ImageField<never>

	/**
	 * Logo (Dark) field in *Header*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: header.logo_dark
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	logo_dark: prismic.ImageField<never>

	/**
	 * Main menu items field in *Header*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: header.menu_items[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	menu_items: prismic.GroupField<Simplify<HeaderDocumentDataMenuItemsItem>>

	/**
	 * CTA Link field in *Header*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: header.cta_link
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	cta_link: prismic.LinkField<
		string,
		string,
		unknown,
		prismic.FieldState,
		never
	>
}

/**
 * Header document from Prismic
 *
 * - **API ID**: `header`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeaderDocument<Lang extends string = string> =
	prismic.PrismicDocumentWithoutUID<
		Simplify<HeaderDocumentData>,
		'header',
		Lang
	>

type HomepageDocumentDataSlicesSlice =
	| TrustedBySlice
	| AssuranceWithImagesSlice
	| IndependentDesignSlice
	| PillarsSlice
	| ValuePropositionSlice
	| HeroStatementSlice

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
	/**
	 * Slice Zone field in *Homepage*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
	 * Meta Title field in *Homepage*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: homepage.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_title: prismic.KeyTextField

	/**
	 * Meta Description field in *Homepage*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: homepage.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_description: prismic.KeyTextField

	/**
	 * Meta Image field in *Homepage*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	meta_image: prismic.ImageField<never>
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
	prismic.PrismicDocumentWithoutUID<
		Simplify<HomepageDocumentData>,
		'homepage',
		Lang
	>

/**
 * Item in *Open role → Tags*
 */
export interface OpenRoleDocumentDataTagsItem {
	/**
	 * Tag field in *Open role → Tags*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: open_role.tags[].tag
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	tag: prismic.KeyTextField
}

/**
 * Content for Open role documents
 */
interface OpenRoleDocumentData {
	/**
	 * Title field in *Open role*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: open_role.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField

	/**
	 * Summary field in *Open role*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: open_role.summary
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	summary: prismic.KeyTextField

	/**
	 * Content field in *Open role*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: open_role.content
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	content: prismic.RichTextField

	/**
	 * Tags field in *Open role*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: open_role.tags[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	tags: prismic.GroupField<Simplify<OpenRoleDocumentDataTagsItem>>
}

/**
 * Open role document from Prismic
 *
 * - **API ID**: `open_role`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type OpenRoleDocument<Lang extends string = string> =
	prismic.PrismicDocumentWithUID<
		Simplify<OpenRoleDocumentData>,
		'open_role',
		Lang
	>

type PageDocumentDataSlicesSlice =
	| ServiceOverviewSlice
	| HeroWithSplitVisualSlice
	| ImageTextColumnsSlice
	| MarqueeTextSlice
	| HeroWithBackgroundSlice
	| FeatureIntroDoubleColumnSlice
	| FeatureGrid2Slice
	| FeatureGridSlice
	| CtaProfileContactSlice
	| CenteredMessageSlice
	| ImageTextColumns2Slice
	| HighlightedTextBlockSlice
	| ContentHeroSlice
	| TrustedBySlice
	| AssuranceWithImagesSlice
	| IndependentDesignSlice
	| PillarsSlice
	| HeroStatementSlice
	| ValuePropositionSlice

/**
 * Content for Page documents
 */
interface PageDocumentData {
	/**
	 * Title field in *Page*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField

	/**
	 * Slice Zone field in *Page*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
	 * Meta Title field in *Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: page.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_title: prismic.KeyTextField

	/**
	 * Meta Description field in *Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: page.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_description: prismic.KeyTextField

	/**
	 * Meta Image field in *Page*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	meta_image: prismic.ImageField<never>
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
	prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, 'page', Lang>

/**
 * Content for Site settings documents
 */
interface SiteSettingsDocumentData {
	/**
	 * Site logo field in *Site settings*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: site_settings.site_logo
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	site_logo: prismic.ImageField<never>

	/**
	 * Contact link field in *Site settings*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: site_settings.contact_link
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	contact_link: prismic.LinkField<
		string,
		string,
		unknown,
		prismic.FieldState,
		never
	>
}

/**
 * Site settings document from Prismic
 *
 * - **API ID**: `site_settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SiteSettingsDocument<Lang extends string = string> =
	prismic.PrismicDocumentWithoutUID<
		Simplify<SiteSettingsDocumentData>,
		'site_settings',
		Lang
	>

/**
 * Item in *Social links → Socials*
 */
export interface SocialLinksDocumentDataSocialsItem {
	/**
	 * Social link field in *Social links → Socials*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: LinkedIn
	 * - **API ID Path**: social_links.socials[].social_link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	social_link: prismic.LinkField<
		string,
		string,
		unknown,
		prismic.FieldState,
		'linkedin' | 'instagram' | 'tiktok' | 'facebook' | 'email'
	>
}

/**
 * Content for Social links documents
 */
interface SocialLinksDocumentData {
	/**
	 * Socials field in *Social links*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: social_links.socials[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	socials: prismic.GroupField<Simplify<SocialLinksDocumentDataSocialsItem>>
}

/**
 * Social links document from Prismic
 *
 * - **API ID**: `social_links`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SocialLinksDocument<Lang extends string = string> =
	prismic.PrismicDocumentWithoutUID<
		Simplify<SocialLinksDocumentData>,
		'social_links',
		Lang
	>

/**
 * Content for Submenu documents
 */
interface SubMenuDocumentData {
	/**
	 * Submenu item field in *Submenu*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: sub_menu.submenu_item
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	submenu_item: prismic.Repeatable<
		prismic.LinkField<string, string, unknown, prismic.FieldState, never>
	>
}

/**
 * Submenu document from Prismic
 *
 * - **API ID**: `sub_menu`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SubMenuDocument<Lang extends string = string> =
	prismic.PrismicDocumentWithUID<
		Simplify<SubMenuDocumentData>,
		'sub_menu',
		Lang
	>

type UnderConstructionPageDocumentDataSlicesSlice = ComingSoonSlice

/**
 * Content for Under Construction Page documents
 */
interface UnderConstructionPageDocumentData {
	/**
	 * Slice Zone field in *Under Construction Page*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: under_construction_page.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	slices: prismic.SliceZone<UnderConstructionPageDocumentDataSlicesSlice> /**
	 * Meta Title field in *Under Construction Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: under_construction_page.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_title: prismic.KeyTextField

	/**
	 * Meta Description field in *Under Construction Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: under_construction_page.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_description: prismic.KeyTextField

	/**
	 * Meta Image field in *Under Construction Page*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: under_construction_page.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	meta_image: prismic.ImageField<never>
}

/**
 * Under Construction Page document from Prismic
 *
 * - **API ID**: `under_construction_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type UnderConstructionPageDocument<Lang extends string = string> =
	prismic.PrismicDocumentWithoutUID<
		Simplify<UnderConstructionPageDocumentData>,
		'under_construction_page',
		Lang
	>

export type AllDocumentTypes =
	| AdvisorySubpageDocument
	| AssuranceSubpageDocument
	| FooterDocument
	| HeaderDocument
	| HomepageDocument
	| OpenRoleDocument
	| PageDocument
	| SiteSettingsDocument
	| SocialLinksDocument
	| SubMenuDocument
	| UnderConstructionPageDocument

/**
 * Item in *FloatingImages → Default → Primary → Images*
 */
export interface AssuranceWithImagesSliceDefaultPrimaryImagesItem {
	/**
	 * Image field in *FloatingImages → Default → Primary → Images*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: assurance_with_images.default.primary.images[].image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>
}

/**
 * Primary content in *FloatingImages → Default → Primary*
 */
export interface AssuranceWithImagesSliceDefaultPrimary {
	/**
	 * Heading field in *FloatingImages → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Enter heading
	 * - **API ID Path**: assurance_with_images.default.primary.heading
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	heading: prismic.RichTextField

	/**
	 * Body field in *FloatingImages → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Enter body text
	 * - **API ID Path**: assurance_with_images.default.primary.body
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	body: prismic.RichTextField

	/**
	 * CTA Link field in *FloatingImages → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: assurance_with_images.default.primary.ctaLink
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	ctaLink: prismic.LinkField<string, string, unknown, prismic.FieldState, never>

	/**
	 * Images field in *FloatingImages → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: assurance_with_images.default.primary.images[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	images: prismic.GroupField<
		Simplify<AssuranceWithImagesSliceDefaultPrimaryImagesItem>
	>
}

/**
 * Default variation for FloatingImages Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AssuranceWithImagesSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<AssuranceWithImagesSliceDefaultPrimary>,
	never
>

/**
 * Slice variation for *FloatingImages*
 */
type AssuranceWithImagesSliceVariation = AssuranceWithImagesSliceDefault

/**
 * FloatingImages Shared Slice
 *
 * - **API ID**: `assurance_with_images`
 * - **Description**: Section with heading, body text, CTA link, and multiple accompanying images
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AssuranceWithImagesSlice = prismic.SharedSlice<
	'assurance_with_images',
	AssuranceWithImagesSliceVariation
>

/**
 * Item in *StickyTitleSection → Simple Centered Text → Primary → Items*
 */
export interface CenteredMessageSliceSimpleCenteredTextPrimaryItemsItem {
	/**
	 * Headline field in *StickyTitleSection → Simple Centered Text → Primary → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: centered_message.simple_centered_text.primary.items[].headline
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	headline: prismic.KeyTextField
}

/**
 * Primary content in *StickyTitleSection → Simple Centered Text → Primary*
 */
export interface CenteredMessageSliceSimpleCenteredTextPrimary {
	/**
	 * Items field in *StickyTitleSection → Simple Centered Text → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: centered_message.simple_centered_text.primary.items[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	items: prismic.GroupField<
		Simplify<CenteredMessageSliceSimpleCenteredTextPrimaryItemsItem>
	>
}

/**
 * Simple Centered Text variation for StickyTitleSection Slice
 *
 * - **API ID**: `simple_centered_text`
 * - **Description**: A single, visually centered message in the section, typically used for slogans, value statements, or important notes without media or decoration.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CenteredMessageSliceSimpleCenteredText =
	prismic.SharedSliceVariation<
		'simple_centered_text',
		Simplify<CenteredMessageSliceSimpleCenteredTextPrimary>,
		never
	>

/**
 * Slice variation for *StickyTitleSection*
 */
type CenteredMessageSliceVariation = CenteredMessageSliceSimpleCenteredText

/**
 * StickyTitleSection Shared Slice
 *
 * - **API ID**: `centered_message`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CenteredMessageSlice = prismic.SharedSlice<
	'centered_message',
	CenteredMessageSliceVariation
>

/**
 * Item in *ComingSoon → Default → Primary → Tags*
 */
export interface ComingSoonSliceDefaultPrimaryTagsItem {
	/**
	 * Tag field in *ComingSoon → Default → Primary → Tags*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: coming_soon.default.primary.tags[].tag
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	tag: prismic.KeyTextField
}

/**
 * Item in *ComingSoon → Default → Primary → Images*
 */
export interface ComingSoonSliceDefaultPrimaryImagesItem {
	/**
	 * Image field in *ComingSoon → Default → Primary → Images*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: coming_soon.default.primary.images[].image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>
}

/**
 * Item in *ComingSoon → Default → Primary → Bottom texts*
 */
export interface ComingSoonSliceDefaultPrimaryBottomTextsItem {
	/**
	 * Bottom text field in *ComingSoon → Default → Primary → Bottom texts*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: coming_soon.default.primary.bottom_texts[].bottom_text
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	bottom_text: prismic.RichTextField
}

/**
 * Primary content in *ComingSoon → Default → Primary*
 */
export interface ComingSoonSliceDefaultPrimary {
	/**
	 * Tags field in *ComingSoon → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: coming_soon.default.primary.tags[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	tags: prismic.GroupField<Simplify<ComingSoonSliceDefaultPrimaryTagsItem>>

	/**
	 * Main Heading field in *ComingSoon → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: coming_soon.default.primary.heading
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	heading: prismic.RichTextField

	/**
	 * Social Links field in *ComingSoon → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: coming_soon.default.primary.social_links
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	social_links: prismic.Repeatable<
		prismic.LinkField<string, string, unknown, prismic.FieldState, never>
	>

	/**
	 * Images field in *ComingSoon → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: coming_soon.default.primary.images[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	images: prismic.GroupField<Simplify<ComingSoonSliceDefaultPrimaryImagesItem>>

	/**
	 * Bottom texts field in *ComingSoon → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: coming_soon.default.primary.bottom_texts[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	bottom_texts: prismic.GroupField<
		Simplify<ComingSoonSliceDefaultPrimaryBottomTextsItem>
	>
}

/**
 * Default variation for ComingSoon Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default coming soon variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ComingSoonSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<ComingSoonSliceDefaultPrimary>,
	never
>

/**
 * Slice variation for *ComingSoon*
 */
type ComingSoonSliceVariation = ComingSoonSliceDefault

/**
 * ComingSoon Shared Slice
 *
 * - **API ID**: `coming_soon`
 * - **Description**: A coming soon landing page with tagline, main heading, and social links
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ComingSoonSlice = prismic.SharedSlice<
	'coming_soon',
	ComingSoonSliceVariation
>

/**
 * Primary content in *CareersHero → Visual Right → Primary*
 */
export interface ContentHeroSliceVisualRightPrimary {
	/**
	 * Headline field in *CareersHero → Visual Right → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: content_hero.visual_right.primary.headline
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	headline: prismic.KeyTextField

	/**
	 * Description field in *CareersHero → Visual Right → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: content_hero.visual_right.primary.description
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	description: prismic.RichTextField

	/**
	 * Call to Action Buttons field in *CareersHero → Visual Right → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: content_hero.visual_right.primary.actions
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	actions: prismic.Repeatable<
		prismic.LinkField<
			string,
			string,
			unknown,
			prismic.FieldState,
			'primary' | 'secondary'
		>
	>

	/**
	 * Main Visual field in *CareersHero → Visual Right → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: content_hero.visual_right.primary.main_visual
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	main_visual: prismic.ImageField<never>
}

/**
 * Visual Right variation for CareersHero Slice
 *
 * - **API ID**: `visual_right`
 * - **Description**: Main visual/image displayed on the right, with text and buttons on the left.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContentHeroSliceVisualRight = prismic.SharedSliceVariation<
	'visual_right',
	Simplify<ContentHeroSliceVisualRightPrimary>,
	never
>

/**
 * Slice variation for *CareersHero*
 */
type ContentHeroSliceVariation = ContentHeroSliceVisualRight

/**
 * CareersHero Shared Slice
 *
 * - **API ID**: `content_hero`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContentHeroSlice = prismic.SharedSlice<
	'content_hero',
	ContentHeroSliceVariation
>

/**
 * Primary content in *CtaProfileContact → Default → Primary*
 */
export interface CtaProfileContactSliceDefaultPrimary {
	/**
	 * Headline field in *CtaProfileContact → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cta_profile_contact.default.primary.headline
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	headline: prismic.KeyTextField

	/**
	 * Side Image field in *CtaProfileContact → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cta_profile_contact.default.primary.image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>

	/**
	 * Main text field in *CtaProfileContact → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cta_profile_contact.default.primary.main_text
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	main_text: prismic.KeyTextField

	/**
	 * Sub Text field in *CtaProfileContact → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cta_profile_contact.default.primary.sub_text
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	sub_text: prismic.RichTextField

	/**
	 * Primary CTA field in *CtaProfileContact → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cta_profile_contact.default.primary.primary_cta
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	primary_cta: prismic.LinkField<
		string,
		string,
		unknown,
		prismic.FieldState,
		never
	>
}

/**
 * Default variation for CtaProfileContact Slice
 *
 * - **API ID**: `default`
 * - **Description**: Standard layout with headline, image on left, info and CTA on right, and a compact contact profile card below call to action.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaProfileContactSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<CtaProfileContactSliceDefaultPrimary>,
	never
>

/**
 * Slice variation for *CtaProfileContact*
 */
type CtaProfileContactSliceVariation = CtaProfileContactSliceDefault

/**
 * CtaProfileContact Shared Slice
 *
 * - **API ID**: `cta_profile_contact`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaProfileContactSlice = prismic.SharedSlice<
	'cta_profile_contact',
	CtaProfileContactSliceVariation
>

/**
 * Item in *FeatureGrid → Default → Primary → Features*
 */
export interface FeatureGridSliceDefaultPrimaryFeaturesItem {
	/**
	 * Icon field in *FeatureGrid → Default → Primary → Features*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: feature_grid.default.primary.features[].icon
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	icon: prismic.ImageField<never>

	/**
	 * Description field in *FeatureGrid → Default → Primary → Features*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: feature_grid.default.primary.features[].description
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	description: prismic.RichTextField
}

/**
 * Primary content in *FeatureGrid → Default → Primary*
 */
export interface FeatureGridSliceDefaultPrimary {
	/**
	 * Heading field in *FeatureGrid → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: feature_grid.default.primary.heading
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	heading: prismic.KeyTextField

	/**
	 * Features field in *FeatureGrid → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: feature_grid.default.primary.features[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	features: prismic.GroupField<
		Simplify<FeatureGridSliceDefaultPrimaryFeaturesItem>
	>
}

/**
 * Default variation for FeatureGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Renders a heading and a grid of feature items, where each item includes an image/icon and supporting description.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeatureGridSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<FeatureGridSliceDefaultPrimary>,
	never
>

/**
 * Slice variation for *FeatureGrid*
 */
type FeatureGridSliceVariation = FeatureGridSliceDefault

/**
 * FeatureGrid Shared Slice
 *
 * - **API ID**: `feature_grid`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeatureGridSlice = prismic.SharedSlice<
	'feature_grid',
	FeatureGridSliceVariation
>

/**
 * Item in *FeatureGrid2 → Default → Primary → Features*
 */
export interface FeatureGrid2SliceDefaultPrimaryFeaturesItem {
	/**
	 * Icon field in *FeatureGrid2 → Default → Primary → Features*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: feature_grid_2.default.primary.features[].icon
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	icon: prismic.ImageField<never>

	/**
	 * Description field in *FeatureGrid2 → Default → Primary → Features*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: feature_grid_2.default.primary.features[].description
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	description: prismic.RichTextField

	/**
	 * CTA Link field in *FeatureGrid2 → Default → Primary → Features*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: feature_grid_2.default.primary.features[].cta_link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	cta_link: prismic.LinkField<
		string,
		string,
		unknown,
		prismic.FieldState,
		never
	>
}

/**
 * Primary content in *FeatureGrid2 → Default → Primary*
 */
export interface FeatureGrid2SliceDefaultPrimary {
	/**
	 * Heading field in *FeatureGrid2 → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: feature_grid_2.default.primary.heading
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	heading: prismic.KeyTextField

	/**
	 * Features field in *FeatureGrid2 → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: feature_grid_2.default.primary.features[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	features: prismic.GroupField<
		Simplify<FeatureGrid2SliceDefaultPrimaryFeaturesItem>
	>
}

/**
 * Default variation for FeatureGrid2 Slice
 *
 * - **API ID**: `default`
 * - **Description**: Shows a heading with a 2-row, multi-column grid of feature cards featuring icons, descriptions, and a call-to-action link per card.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeatureGrid2SliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<FeatureGrid2SliceDefaultPrimary>,
	never
>

/**
 * Slice variation for *FeatureGrid2*
 */
type FeatureGrid2SliceVariation = FeatureGrid2SliceDefault

/**
 * FeatureGrid2 Shared Slice
 *
 * - **API ID**: `feature_grid_2`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeatureGrid2Slice = prismic.SharedSlice<
	'feature_grid_2',
	FeatureGrid2SliceVariation
>

/**
 * Primary content in *FeatureIntroDoubleColumn → Default → Primary*
 */
export interface FeatureIntroDoubleColumnSliceDefaultPrimary {
	/**
	 * Heading field in *FeatureIntroDoubleColumn → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: feature_intro_double_column.default.primary.heading
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	heading: prismic.KeyTextField

	/**
	 * Description field in *FeatureIntroDoubleColumn → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: feature_intro_double_column.default.primary.description
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	description: prismic.RichTextField

	/**
	 * Shape field in *FeatureIntroDoubleColumn → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **API ID Path**: feature_intro_double_column.default.primary.shape
	 * - **Documentation**: https://prismic.io/docs/fields/select
	 */
	shape: prismic.SelectField<
		'roundVerticalLines' | 'roundWorldShape' | 'TriangleShape' | 'squareShape'
	>

	/**
	 * Highlight field in *FeatureIntroDoubleColumn → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: feature_intro_double_column.default.primary.highlight
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	highlight: prismic.KeyTextField

	/**
	 * Supporting Text field in *FeatureIntroDoubleColumn → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: feature_intro_double_column.default.primary.supporting_text
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	supporting_text: prismic.RichTextField
}

/**
 * Default variation for FeatureIntroDoubleColumn Slice
 *
 * - **API ID**: `default`
 * - **Description**: Standard two-column intro with heading, description, image, and supporting statement.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeatureIntroDoubleColumnSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<FeatureIntroDoubleColumnSliceDefaultPrimary>,
	never
>

/**
 * Slice variation for *FeatureIntroDoubleColumn*
 */
type FeatureIntroDoubleColumnSliceVariation =
	FeatureIntroDoubleColumnSliceDefault

/**
 * FeatureIntroDoubleColumn Shared Slice
 *
 * - **API ID**: `feature_intro_double_column`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeatureIntroDoubleColumnSlice = prismic.SharedSlice<
	'feature_intro_double_column',
	FeatureIntroDoubleColumnSliceVariation
>

/**
 * Item in *HeroHomepage → Default → Primary → Tags*
 */
export interface HeroStatementSliceDefaultPrimaryTagsItem {
	/**
	 * Tag field in *HeroHomepage → Default → Primary → Tags*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_statement.default.primary.tags[].tag
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	tag: prismic.KeyTextField
}

/**
 * Item in *HeroHomepage → Default → Primary → Address lines*
 */
export interface HeroStatementSliceDefaultPrimaryAddressLinesItem {
	/**
	 * Line field in *HeroHomepage → Default → Primary → Address lines*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_statement.default.primary.address_lines[].line
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	line: prismic.KeyTextField
}

/**
 * Item in *HeroHomepage → Default → Primary → Gallery*
 */
export interface HeroStatementSliceDefaultPrimaryGalleryItem {
	/**
	 * Image field in *HeroHomepage → Default → Primary → Gallery*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_statement.default.primary.gallery[].image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>

	/**
	 * Video field in *HeroHomepage → Default → Primary → Gallery*
	 *
	 * - **Field Type**: Link to Media
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_statement.default.primary.gallery[].video
	 * - **Documentation**: https://prismic.io/docs/fields/link-to-media
	 */
	video: prismic.LinkToMediaField<prismic.FieldState, never>
}

/**
 * Primary content in *HeroHomepage → Default → Primary*
 */
export interface HeroStatementSliceDefaultPrimary {
	/**
	 * Tags field in *HeroHomepage → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_statement.default.primary.tags[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	tags: prismic.GroupField<Simplify<HeroStatementSliceDefaultPrimaryTagsItem>>

	/**
	 * Heading field in *HeroHomepage → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: e.g., We create trust in a digital world.
	 * - **API ID Path**: hero_statement.default.primary.heading
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	heading: prismic.RichTextField

	/**
	 * Address lines field in *HeroHomepage → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_statement.default.primary.address_lines[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	address_lines: prismic.GroupField<
		Simplify<HeroStatementSliceDefaultPrimaryAddressLinesItem>
	>

	/**
	 * Scroll Hint field in *HeroHomepage → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: e.g., (Scroll for more)
	 * - **API ID Path**: hero_statement.default.primary.scrollHint
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	scrollHint: prismic.KeyTextField

	/**
	 * Gallery field in *HeroHomepage → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_statement.default.primary.gallery[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	gallery: prismic.GroupField<
		Simplify<HeroStatementSliceDefaultPrimaryGalleryItem>
	>
}

/**
 * Default variation for HeroHomepage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default hero statement variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroStatementSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<HeroStatementSliceDefaultPrimary>,
	never
>

/**
 * Slice variation for *HeroHomepage*
 */
type HeroStatementSliceVariation = HeroStatementSliceDefault

/**
 * HeroHomepage Shared Slice
 *
 * - **API ID**: `hero_statement`
 * - **Description**: Hero section with tagline, main heading, address, scroll hint, and image gallery
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroStatementSlice = prismic.SharedSlice<
	'hero_statement',
	HeroStatementSliceVariation
>

/**
 * Primary content in *HeroWithBackground → Default → Primary*
 */
export interface HeroWithBackgroundSliceDefaultPrimary {
	/**
	 * Background image field in *HeroWithBackground → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_with_background.default.primary.background_image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	background_image: prismic.ImageField<never>

	/**
	 * Background video field in *HeroWithBackground → Default → Primary*
	 *
	 * - **Field Type**: Link to Media
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_with_background.default.primary.background_video
	 * - **Documentation**: https://prismic.io/docs/fields/link-to-media
	 */
	background_video: prismic.LinkToMediaField<prismic.FieldState, never>

	/**
	 * Headline field in *HeroWithBackground → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_with_background.default.primary.headline
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	headline: prismic.KeyTextField

	/**
	 * CTA button field in *HeroWithBackground → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_with_background.default.primary.cta_button
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	cta_button: prismic.Repeatable<
		prismic.LinkField<
			string,
			string,
			unknown,
			prismic.FieldState,
			'primary' | 'secondary'
		>
	>
}

/**
 * Default variation for HeroWithBackground Slice
 *
 * - **API ID**: `default`
 * - **Description**: Standard hero with background image, headline, and two adjacent buttons.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroWithBackgroundSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<HeroWithBackgroundSliceDefaultPrimary>,
	never
>

/**
 * Slice variation for *HeroWithBackground*
 */
type HeroWithBackgroundSliceVariation = HeroWithBackgroundSliceDefault

/**
 * HeroWithBackground Shared Slice
 *
 * - **API ID**: `hero_with_background`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroWithBackgroundSlice = prismic.SharedSlice<
	'hero_with_background',
	HeroWithBackgroundSliceVariation
>

/**
 * Primary content in *HeroWithSplitVisual → Default → Primary*
 */
export interface HeroWithSplitVisualSliceDefaultPrimary {
	/**
	 * Page title field in *HeroWithSplitVisual → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_with_split_visual.default.primary.page_title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	page_title: prismic.KeyTextField

	/**
	 * Visual field in *HeroWithSplitVisual → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_with_split_visual.default.primary.visual
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	visual: prismic.ImageField<never>
}

/**
 * Default variation for HeroWithSplitVisual Slice
 *
 * - **API ID**: `default`
 * - **Description**: Standard hero layout with content on the left and an image on the right.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroWithSplitVisualSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<HeroWithSplitVisualSliceDefaultPrimary>,
	never
>

/**
 * Slice variation for *HeroWithSplitVisual*
 */
type HeroWithSplitVisualSliceVariation = HeroWithSplitVisualSliceDefault

/**
 * HeroWithSplitVisual Shared Slice
 *
 * - **API ID**: `hero_with_split_visual`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroWithSplitVisualSlice = prismic.SharedSlice<
	'hero_with_split_visual',
	HeroWithSplitVisualSliceVariation
>

/**
 * Primary content in *RevealTypeBlock → default → Primary*
 */
export interface HighlightedTextBlockSliceWithSecondaryStatementPrimary {
	/**
	 * Content field in *RevealTypeBlock → default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: highlighted_text_block.with_secondary_statement.primary.content
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	content: prismic.KeyTextField
}

/**
 * default variation for RevealTypeBlock Slice
 *
 * - **API ID**: `with_secondary_statement`
 * - **Description**: Variation for displaying a main highlighted message, a supporting paragraph, and a secondary statement/quote below.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HighlightedTextBlockSliceWithSecondaryStatement =
	prismic.SharedSliceVariation<
		'with_secondary_statement',
		Simplify<HighlightedTextBlockSliceWithSecondaryStatementPrimary>,
		never
	>

/**
 * Slice variation for *RevealTypeBlock*
 */
type HighlightedTextBlockSliceVariation =
	HighlightedTextBlockSliceWithSecondaryStatement

/**
 * RevealTypeBlock Shared Slice
 *
 * - **API ID**: `highlighted_text_block`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HighlightedTextBlockSlice = prismic.SharedSlice<
	'highlighted_text_block',
	HighlightedTextBlockSliceVariation
>

/**
 * Item in *ImageTextColumns → Alternating Image & Text Blocks → Primary → Blocks*
 */
export interface ImageTextColumnsSliceAlternatingBlocksPrimaryBlocksItem {
	/**
	 * Image field in *ImageTextColumns → Alternating Image & Text Blocks → Primary → Blocks*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: image_text_columns.alternating_blocks.primary.blocks[].image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>

	/**
	 * Image Position field in *ImageTextColumns → Alternating Image & Text Blocks → Primary → Blocks*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **API ID Path**: image_text_columns.alternating_blocks.primary.blocks[].image_position
	 * - **Documentation**: https://prismic.io/docs/fields/select
	 */
	image_position: prismic.SelectField<'left' | 'right'>

	/**
	 * Heading field in *ImageTextColumns → Alternating Image & Text Blocks → Primary → Blocks*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: image_text_columns.alternating_blocks.primary.blocks[].heading
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	heading: prismic.KeyTextField

	/**
	 * Description field in *ImageTextColumns → Alternating Image & Text Blocks → Primary → Blocks*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: image_text_columns.alternating_blocks.primary.blocks[].description
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	description: prismic.RichTextField
}

/**
 * Primary content in *ImageTextColumns → Alternating Image & Text Blocks → Primary*
 */
export interface ImageTextColumnsSliceAlternatingBlocksPrimary {
	/**
	 * Blocks field in *ImageTextColumns → Alternating Image & Text Blocks → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: image_text_columns.alternating_blocks.primary.blocks[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	blocks: prismic.GroupField<
		Simplify<ImageTextColumnsSliceAlternatingBlocksPrimaryBlocksItem>
	>
}

/**
 * Alternating Image & Text Blocks variation for ImageTextColumns Slice
 *
 * - **API ID**: `alternating_blocks`
 * - **Description**: Alternates between text and image per block with flexible order and emphasis. Each block can independently define heading, subheading, description, and image.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageTextColumnsSliceAlternatingBlocks =
	prismic.SharedSliceVariation<
		'alternating_blocks',
		Simplify<ImageTextColumnsSliceAlternatingBlocksPrimary>,
		never
	>

/**
 * Slice variation for *ImageTextColumns*
 */
type ImageTextColumnsSliceVariation = ImageTextColumnsSliceAlternatingBlocks

/**
 * ImageTextColumns Shared Slice
 *
 * - **API ID**: `image_text_columns`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageTextColumnsSlice = prismic.SharedSlice<
	'image_text_columns',
	ImageTextColumnsSliceVariation
>

/**
 * Primary content in *ImageTextBlock → ImageTextBlock → Primary*
 */
export interface ImageTextColumns2SliceImageLeftTextRightPrimary {
	/**
	 * Image field in *ImageTextBlock → ImageTextBlock → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: image_text_columns_2.image_left_text_right.primary.media
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	media: prismic.ImageField<never>

	/**
	 * Headline field in *ImageTextBlock → ImageTextBlock → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: image_text_columns_2.image_left_text_right.primary.headline
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	headline: prismic.KeyTextField

	/**
	 * Description field in *ImageTextBlock → ImageTextBlock → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: image_text_columns_2.image_left_text_right.primary.description
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	description: prismic.RichTextField
}

/**
 * ImageTextBlock variation for ImageTextBlock Slice
 *
 * - **API ID**: `image_left_text_right`
 * - **Description**: Displays an image on the left side and title/description rich text content on the right. Ideal for informative or narrative sections paired with a visual.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageTextColumns2SliceImageLeftTextRight =
	prismic.SharedSliceVariation<
		'image_left_text_right',
		Simplify<ImageTextColumns2SliceImageLeftTextRightPrimary>,
		never
	>

/**
 * Slice variation for *ImageTextBlock*
 */
type ImageTextColumns2SliceVariation = ImageTextColumns2SliceImageLeftTextRight

/**
 * ImageTextBlock Shared Slice
 *
 * - **API ID**: `image_text_columns_2`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageTextColumns2Slice = prismic.SharedSlice<
	'image_text_columns_2',
	ImageTextColumns2SliceVariation
>

/**
 * Item in *StickyFeatures → Default → Primary → Features*
 */
export interface IndependentDesignSliceDefaultPrimaryFeaturesItem {
	/**
	 * Image field in *StickyFeatures → Default → Primary → Features*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: independent_design.default.primary.features[].image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>

	/**
	 * Heading field in *StickyFeatures → Default → Primary → Features*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: independent_design.default.primary.features[].heading
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	heading: prismic.KeyTextField

	/**
	 * Description field in *StickyFeatures → Default → Primary → Features*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: independent_design.default.primary.features[].description
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	description: prismic.RichTextField

	/**
	 * CTA Link field in *StickyFeatures → Default → Primary → Features*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: independent_design.default.primary.features[].cta_link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	cta_link: prismic.LinkField<
		string,
		string,
		unknown,
		prismic.FieldState,
		never
	>
}

/**
 * Primary content in *StickyFeatures → Default → Primary*
 */
export interface IndependentDesignSliceDefaultPrimary {
	/**
	 * Features field in *StickyFeatures → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: independent_design.default.primary.features[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	features: prismic.GroupField<
		Simplify<IndependentDesignSliceDefaultPrimaryFeaturesItem>
	>
}

/**
 * Default variation for StickyFeatures Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation with image on left and content on right
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type IndependentDesignSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<IndependentDesignSliceDefaultPrimary>,
	never
>

/**
 * Slice variation for *StickyFeatures*
 */
type IndependentDesignSliceVariation = IndependentDesignSliceDefault

/**
 * StickyFeatures Shared Slice
 *
 * - **API ID**: `independent_design`
 * - **Description**: Hero section with badge, heading, description, image, and CTA button
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type IndependentDesignSlice = prismic.SharedSlice<
	'independent_design',
	IndependentDesignSliceVariation
>

/**
 * Item in *MarqueeText → Default → Primary → Items*
 */
export interface MarqueeTextSliceDefaultPrimaryItemsItem {
	/**
	 * Marquee Text field in *MarqueeText → Default → Primary → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: marquee_text.default.primary.items[].marquee_text
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	marquee_text: prismic.KeyTextField
}

/**
 * Primary content in *MarqueeText → Default → Primary*
 */
export interface MarqueeTextSliceDefaultPrimary {
	/**
	 * Items field in *MarqueeText → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: marquee_text.default.primary.items[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	items: prismic.GroupField<Simplify<MarqueeTextSliceDefaultPrimaryItemsItem>>
}

/**
 * Default variation for MarqueeText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Simple horizontal marquee of text items with separators.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MarqueeTextSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<MarqueeTextSliceDefaultPrimary>,
	never
>

/**
 * Slice variation for *MarqueeText*
 */
type MarqueeTextSliceVariation = MarqueeTextSliceDefault

/**
 * MarqueeText Shared Slice
 *
 * - **API ID**: `marquee_text`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MarqueeTextSlice = prismic.SharedSlice<
	'marquee_text',
	MarqueeTextSliceVariation
>

/**
 * Item in *FeatureCards → Default → Primary → Pillars*
 */
export interface PillarsSliceDefaultPrimaryPillarsItem {
	/**
	 * Title field in *FeatureCards → Default → Primary → Pillars*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: pillars.default.primary.pillars[].title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField

	/**
	 * Description field in *FeatureCards → Default → Primary → Pillars*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: pillars.default.primary.pillars[].description
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	description: prismic.RichTextField

	/**
	 * Index field in *FeatureCards → Default → Primary → Pillars*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: pillars.default.primary.pillars[].index
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	index: prismic.KeyTextField

	/**
	 * Background Color field in *FeatureCards → Default → Primary → Pillars*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: *None*
	 * - **API ID Path**: pillars.default.primary.pillars[].background_color
	 * - **Documentation**: https://prismic.io/docs/fields/color
	 */
	background_color: prismic.ColorField

	/**
	 * Text color field in *FeatureCards → Default → Primary → Pillars*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: *None*
	 * - **API ID Path**: pillars.default.primary.pillars[].text_color
	 * - **Documentation**: https://prismic.io/docs/fields/color
	 */
	text_color: prismic.ColorField

	/**
	 * Shape field in *FeatureCards → Default → Primary → Pillars*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: roundVerticalLines
	 * - **API ID Path**: pillars.default.primary.pillars[].shape
	 * - **Documentation**: https://prismic.io/docs/fields/select
	 */
	shape: prismic.SelectField<
		'roundVerticalLines' | 'roundWorldShape' | 'TriangleShape',
		'filled'
	>
}

/**
 * Item in *FeatureCards → Slider → Primary → Cards*
 */
export interface PillarsSliceSliderPrimaryCardsItem {
	/**
	 * Title field in *FeatureCards → Slider → Primary → Cards*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: pillars.slider.primary.cards[].title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField

	/**
	 * Description field in *FeatureCards → Slider → Primary → Cards*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: pillars.slider.primary.cards[].description
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	description: prismic.RichTextField

	/**
	 * Background color field in *FeatureCards → Slider → Primary → Cards*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: Dark
	 * - **API ID Path**: pillars.slider.primary.cards[].background_color
	 * - **Documentation**: https://prismic.io/docs/fields/select
	 */
	background_color: prismic.SelectField<'Dark' | 'Aqua' | 'Clay', 'filled'>

	/**
	 * Shape field in *FeatureCards → Slider → Primary → Cards*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: Cylinder
	 * - **API ID Path**: pillars.slider.primary.cards[].shape
	 * - **Documentation**: https://prismic.io/docs/fields/select
	 */
	shape: prismic.SelectField<'Cylinder' | 'Sphere' | 'Pyramid', 'filled'>
}

/**
 * Primary content in *FeatureCards → Default → Primary*
 */
export interface PillarsSliceDefaultPrimary {
	/**
	 * Heading field in *FeatureCards → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: pillars.default.primary.heading
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	heading: prismic.RichTextField

	/**
	 * Pillars field in *FeatureCards → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: pillars.default.primary.pillars[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	pillars: prismic.GroupField<Simplify<PillarsSliceDefaultPrimaryPillarsItem>>
}

/**
 * Default variation for FeatureCards Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation of Pillars slice
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PillarsSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<PillarsSliceDefaultPrimary>,
	never
>

/**
 * Primary content in *FeatureCards → Slider → Primary*
 */
export interface PillarsSliceSliderPrimary {
	/**
	 * Heading field in *FeatureCards → Slider → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: pillars.slider.primary.heading
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	heading: prismic.RichTextField

	/**
	 * Cards field in *FeatureCards → Slider → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: pillars.slider.primary.cards[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	cards: prismic.GroupField<Simplify<PillarsSliceSliderPrimaryCardsItem>>
}

/**
 * Slider variation for FeatureCards Slice
 *
 * - **API ID**: `slider`
 * - **Description**: Default variation of Pillars slice
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PillarsSliceSlider = prismic.SharedSliceVariation<
	'slider',
	Simplify<PillarsSliceSliderPrimary>,
	never
>

/**
 * Slice variation for *FeatureCards*
 */
type PillarsSliceVariation = PillarsSliceDefault | PillarsSliceSlider

/**
 * FeatureCards Shared Slice
 *
 * - **API ID**: `pillars`
 * - **Description**: Three pillar cards displaying company values/principles with title, description, and background color
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PillarsSlice = prismic.SharedSlice<'pillars', PillarsSliceVariation>

/**
 * Item in *ServiceOverview → With Slider and Contact → Primary → Service Items*
 */
export interface ServiceOverviewSliceWithSliderAndContactPrimaryServiceItemsItem {
	/**
	 * Service Title field in *ServiceOverview → With Slider and Contact → Primary → Service Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: service_overview.with_slider_and_contact.primary.service_items[].service_title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	service_title: prismic.KeyTextField

	/**
	 * Service Description field in *ServiceOverview → With Slider and Contact → Primary → Service Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: service_overview.with_slider_and_contact.primary.service_items[].service_description
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	service_description: prismic.RichTextField

	/**
	 * Service Image field in *ServiceOverview → With Slider and Contact → Primary → Service Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: service_overview.with_slider_and_contact.primary.service_items[].service_image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	service_image: prismic.ImageField<never>
}

/**
 * Primary content in *ServiceOverview → With Slider and Contact → Primary*
 */
export interface ServiceOverviewSliceWithSliderAndContactPrimary {
	/**
	 * Heading field in *ServiceOverview → With Slider and Contact → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: service_overview.with_slider_and_contact.primary.heading
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	heading: prismic.KeyTextField

	/**
	 * Description field in *ServiceOverview → With Slider and Contact → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: service_overview.with_slider_and_contact.primary.description
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	description: prismic.RichTextField

	/**
	 * Service Items field in *ServiceOverview → With Slider and Contact → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: service_overview.with_slider_and_contact.primary.service_items[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	service_items: prismic.GroupField<
		Simplify<ServiceOverviewSliceWithSliderAndContactPrimaryServiceItemsItem>
	>

	/**
	 * CTA Link field in *ServiceOverview → With Slider and Contact → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: service_overview.with_slider_and_contact.primary.cta_link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	cta_link: prismic.LinkField<
		string,
		string,
		unknown,
		prismic.FieldState,
		never
	>
}

/**
 * With Slider and Contact variation for ServiceOverview Slice
 *
 * - **API ID**: `with_slider_and_contact`
 * - **Description**: Includes an introductory block, prominent contact person, and a horizontally navigable slider showcasing different core services.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServiceOverviewSliceWithSliderAndContact =
	prismic.SharedSliceVariation<
		'with_slider_and_contact',
		Simplify<ServiceOverviewSliceWithSliderAndContactPrimary>,
		never
	>

/**
 * Slice variation for *ServiceOverview*
 */
type ServiceOverviewSliceVariation = ServiceOverviewSliceWithSliderAndContact

/**
 * ServiceOverview Shared Slice
 *
 * - **API ID**: `service_overview`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServiceOverviewSlice = prismic.SharedSlice<
	'service_overview',
	ServiceOverviewSliceVariation
>

/**
 * Item in *TrustedBy → Default → Primary → Logos*
 */
export interface TrustedBySliceDefaultPrimaryLogosItem {
	/**
	 * Logo Image field in *TrustedBy → Default → Primary → Logos*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: trusted_by.default.primary.logos[].logo_image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	logo_image: prismic.ImageField<never>

	/**
	 * With background field in *TrustedBy → Default → Primary → Logos*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: trusted_by.default.primary.logos[].with_background
	 * - **Documentation**: https://prismic.io/docs/fields/boolean
	 */
	with_background: prismic.BooleanField
}

/**
 * Primary content in *TrustedBy → Default → Primary*
 */
export interface TrustedBySliceDefaultPrimary {
	/**
	 * Logos field in *TrustedBy → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: trusted_by.default.primary.logos[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	logos: prismic.GroupField<Simplify<TrustedBySliceDefaultPrimaryLogosItem>>

	/**
	 * Heading field in *TrustedBy → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Trusted by leading organisations
	 * - **API ID Path**: trusted_by.default.primary.heading
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	heading: prismic.KeyTextField
}

/**
 * Default variation for TrustedBy Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation with heading and logo grid
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TrustedBySliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<TrustedBySliceDefaultPrimary>,
	never
>

/**
 * Slice variation for *TrustedBy*
 */
type TrustedBySliceVariation = TrustedBySliceDefault

/**
 * TrustedBy Shared Slice
 *
 * - **API ID**: `trusted_by`
 * - **Description**: A slice showcasing logos of trusted organizations in a grid layout
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TrustedBySlice = prismic.SharedSlice<
	'trusted_by',
	TrustedBySliceVariation
>

/**
 * Primary content in *RevealTypeWithCta → Default → Primary*
 */
export interface ValuePropositionSliceDefaultPrimary {
	/**
	 * Label field in *RevealTypeWithCta → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: e.g., Why Risk Boutique?
	 * - **API ID Path**: value_proposition.default.primary.label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	label: prismic.KeyTextField

	/**
	 * Content field in *RevealTypeWithCta → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: We combine the agility of a boutique with...
	 * - **API ID Path**: value_proposition.default.primary.content
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	content: prismic.KeyTextField

	/**
	 * CTA Link field in *RevealTypeWithCta → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: Talk to us
	 * - **API ID Path**: value_proposition.default.primary.cta_link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	cta_link: prismic.LinkField<
		string,
		string,
		unknown,
		prismic.FieldState,
		never
	>
}

/**
 * Default variation for RevealTypeWithCta Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default value proposition variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ValuePropositionSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<ValuePropositionSliceDefaultPrimary>,
	never
>

/**
 * Slice variation for *RevealTypeWithCta*
 */
type ValuePropositionSliceVariation = ValuePropositionSliceDefault

/**
 * RevealTypeWithCta Shared Slice
 *
 * - **API ID**: `value_proposition`
 * - **Description**: A value proposition section with label, heading, body text, and CTA link
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ValuePropositionSlice = prismic.SharedSlice<
	'value_proposition',
	ValuePropositionSliceVariation
>

declare module '@prismicio/client' {
	interface CreateClient {
		(
			repositoryNameOrEndpoint: string,
			options?: prismic.ClientConfig
		): prismic.Client<AllDocumentTypes>
	}

	interface CreateWriteClient {
		(
			repositoryNameOrEndpoint: string,
			options: prismic.WriteClientConfig
		): prismic.WriteClient<AllDocumentTypes>
	}

	interface CreateMigration {
		(): prismic.Migration<AllDocumentTypes>
	}

	namespace Content {
		export type {
			AdvisorySubpageDocument,
			AdvisorySubpageDocumentData,
			AdvisorySubpageDocumentDataSlicesSlice,
			AssuranceSubpageDocument,
			AssuranceSubpageDocumentData,
			AssuranceSubpageDocumentDataSlicesSlice,
			FooterDocument,
			FooterDocumentData,
			FooterDocumentDataSocialIconsItem,
			FooterDocumentDataColumnsItem,
			HeaderDocument,
			HeaderDocumentData,
			HeaderDocumentDataMenuItemsItem,
			HomepageDocument,
			HomepageDocumentData,
			HomepageDocumentDataSlicesSlice,
			OpenRoleDocument,
			OpenRoleDocumentData,
			OpenRoleDocumentDataTagsItem,
			PageDocument,
			PageDocumentData,
			PageDocumentDataSlicesSlice,
			SiteSettingsDocument,
			SiteSettingsDocumentData,
			SocialLinksDocument,
			SocialLinksDocumentData,
			SocialLinksDocumentDataSocialsItem,
			SubMenuDocument,
			SubMenuDocumentData,
			UnderConstructionPageDocument,
			UnderConstructionPageDocumentData,
			UnderConstructionPageDocumentDataSlicesSlice,
			AllDocumentTypes,
			AssuranceWithImagesSlice,
			AssuranceWithImagesSliceDefaultPrimaryImagesItem,
			AssuranceWithImagesSliceDefaultPrimary,
			AssuranceWithImagesSliceVariation,
			AssuranceWithImagesSliceDefault,
			CenteredMessageSlice,
			CenteredMessageSliceSimpleCenteredTextPrimaryItemsItem,
			CenteredMessageSliceSimpleCenteredTextPrimary,
			CenteredMessageSliceVariation,
			CenteredMessageSliceSimpleCenteredText,
			ComingSoonSlice,
			ComingSoonSliceDefaultPrimaryTagsItem,
			ComingSoonSliceDefaultPrimaryImagesItem,
			ComingSoonSliceDefaultPrimaryBottomTextsItem,
			ComingSoonSliceDefaultPrimary,
			ComingSoonSliceVariation,
			ComingSoonSliceDefault,
			ContentHeroSlice,
			ContentHeroSliceVisualRightPrimary,
			ContentHeroSliceVariation,
			ContentHeroSliceVisualRight,
			CtaProfileContactSlice,
			CtaProfileContactSliceDefaultPrimary,
			CtaProfileContactSliceVariation,
			CtaProfileContactSliceDefault,
			FeatureGridSlice,
			FeatureGridSliceDefaultPrimaryFeaturesItem,
			FeatureGridSliceDefaultPrimary,
			FeatureGridSliceVariation,
			FeatureGridSliceDefault,
			FeatureGrid2Slice,
			FeatureGrid2SliceDefaultPrimaryFeaturesItem,
			FeatureGrid2SliceDefaultPrimary,
			FeatureGrid2SliceVariation,
			FeatureGrid2SliceDefault,
			FeatureIntroDoubleColumnSlice,
			FeatureIntroDoubleColumnSliceDefaultPrimary,
			FeatureIntroDoubleColumnSliceVariation,
			FeatureIntroDoubleColumnSliceDefault,
			HeroStatementSlice,
			HeroStatementSliceDefaultPrimaryTagsItem,
			HeroStatementSliceDefaultPrimaryAddressLinesItem,
			HeroStatementSliceDefaultPrimaryGalleryItem,
			HeroStatementSliceDefaultPrimary,
			HeroStatementSliceVariation,
			HeroStatementSliceDefault,
			HeroWithBackgroundSlice,
			HeroWithBackgroundSliceDefaultPrimary,
			HeroWithBackgroundSliceVariation,
			HeroWithBackgroundSliceDefault,
			HeroWithSplitVisualSlice,
			HeroWithSplitVisualSliceDefaultPrimary,
			HeroWithSplitVisualSliceVariation,
			HeroWithSplitVisualSliceDefault,
			HighlightedTextBlockSlice,
			HighlightedTextBlockSliceWithSecondaryStatementPrimary,
			HighlightedTextBlockSliceVariation,
			HighlightedTextBlockSliceWithSecondaryStatement,
			ImageTextColumnsSlice,
			ImageTextColumnsSliceAlternatingBlocksPrimaryBlocksItem,
			ImageTextColumnsSliceAlternatingBlocksPrimary,
			ImageTextColumnsSliceVariation,
			ImageTextColumnsSliceAlternatingBlocks,
			ImageTextColumns2Slice,
			ImageTextColumns2SliceImageLeftTextRightPrimary,
			ImageTextColumns2SliceVariation,
			ImageTextColumns2SliceImageLeftTextRight,
			IndependentDesignSlice,
			IndependentDesignSliceDefaultPrimaryFeaturesItem,
			IndependentDesignSliceDefaultPrimary,
			IndependentDesignSliceVariation,
			IndependentDesignSliceDefault,
			MarqueeTextSlice,
			MarqueeTextSliceDefaultPrimaryItemsItem,
			MarqueeTextSliceDefaultPrimary,
			MarqueeTextSliceVariation,
			MarqueeTextSliceDefault,
			PillarsSlice,
			PillarsSliceDefaultPrimaryPillarsItem,
			PillarsSliceDefaultPrimary,
			PillarsSliceSliderPrimaryCardsItem,
			PillarsSliceSliderPrimary,
			PillarsSliceVariation,
			PillarsSliceDefault,
			PillarsSliceSlider,
			ServiceOverviewSlice,
			ServiceOverviewSliceWithSliderAndContactPrimaryServiceItemsItem,
			ServiceOverviewSliceWithSliderAndContactPrimary,
			ServiceOverviewSliceVariation,
			ServiceOverviewSliceWithSliderAndContact,
			TrustedBySlice,
			TrustedBySliceDefaultPrimaryLogosItem,
			TrustedBySliceDefaultPrimary,
			TrustedBySliceVariation,
			TrustedBySliceDefault,
			ValuePropositionSlice,
			ValuePropositionSliceDefaultPrimary,
			ValuePropositionSliceVariation,
			ValuePropositionSliceDefault
		}
	}
}
