// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
	TRelationship extends
		| prismic.CustomTypeModelFetchCustomTypeLevel1
		| prismic.CustomTypeModelFetchCustomTypeLevel2
		| prismic.CustomTypeModelFetchGroupLevel1
		| prismic.CustomTypeModelFetchGroupLevel2,
	TData extends Record<
		string,
		prismic.AnyRegularField | prismic.GroupField | prismic.NestedGroupField | prismic.SliceZone
	>,
	TLang extends string
> =
	// Content relationship fields
	{
		[TSubRelationship in Extract<
			TRelationship['fields'][number],
			prismic.CustomTypeModelFetchContentRelationshipLevel1
		> as TSubRelationship['id']]: ContentRelationshipFieldWithData<
			TSubRelationship['customtypes'],
			TLang
		>;
	} & // Group
	{
		[TGroup in Extract<
			TRelationship['fields'][number],
			prismic.CustomTypeModelFetchGroupLevel1 | prismic.CustomTypeModelFetchGroupLevel2
		> as TGroup['id']]: TData[TGroup['id']] extends prismic.GroupField<infer TGroupData>
			? prismic.GroupField<PickContentRelationshipFieldData<TGroup, TGroupData, TLang>>
			: never;
	} & // Other fields
	{
		[TFieldKey in Extract<TRelationship['fields'][number], string>]: TFieldKey extends keyof TData
			? TData[TFieldKey]
			: never;
	};

type ContentRelationshipFieldWithData<
	TCustomType extends
		| readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
		| readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
	TLang extends string = string
> = {
	[ID in Exclude<TCustomType[number], string>['id']]: prismic.ContentRelationshipField<
		ID,
		TLang,
		PickContentRelationshipFieldData<
			Extract<TCustomType[number], { id: ID }>,
			Extract<prismic.Content.AllDocumentTypes, { type: ID }>['data'],
			TLang
		>
	>;
}[Exclude<TCustomType[number], string>['id']];

interface FooterDocumentData {}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<FooterDocumentData>,
	'footer',
	Lang
>;

/**
 * Item in *Header → Main menu items*
 */
export interface HeaderDocumentDataMenuItemsItem {
	/**
	 * Label field in *Header → Main menu items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: header.menu_items[].label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	label: prismic.KeyTextField;

	/**
	 * Link field in *Header → Main menu items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: It's either a link or a sub menu, not both!
	 * - **API ID Path**: header.menu_items[].link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

	/**
	 * Has submenu field in *Header → Main menu items*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: header.menu_items[].has_submenu
	 * - **Documentation**: https://prismic.io/docs/fields/boolean
	 */
	has_submenu: prismic.BooleanField;

	/**
	 * Submenu field in *Header → Main menu items*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: header.menu_items[].submenu
	 * - **Documentation**: https://prismic.io/docs/fields/content-relationship
	 */
	submenu: ContentRelationshipFieldWithData<[{ id: 'sub_menu'; fields: ['submenu_item'] }]>;
}

/**
 * Content for Header documents
 */
interface HeaderDocumentData {
	/**
	 * Logo (Light) field in *Header*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: header.logo_light
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	logo_light: prismic.ImageField<never>;

	/**
	 * Logo (Dark) field in *Header*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: header.logo_dark
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	logo_dark: prismic.ImageField<never>;

	/**
	 * Main menu items field in *Header*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: header.menu_items[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	menu_items: prismic.GroupField<Simplify<HeaderDocumentDataMenuItemsItem>>;

	/**
	 * CTA Link field in *Header*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: header.cta_link
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	cta_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Header document from Prismic
 *
 * - **API ID**: `header`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeaderDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<HeaderDocumentData>,
	'header',
	Lang
>;

type HomepageDocumentDataSlicesSlice =
	| TrustedBySlice
	| AssuranceWithImagesSlice
	| IndependentDesignSlice
	| PillarsSlice
	| ValuePropositionSlice
	| HeroStatementSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
	/**
	 * Slice Zone field in *Homepage*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice>; /**
	 * Meta Title field in *Homepage*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: homepage.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *Homepage*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: homepage.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *Homepage*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<HomepageDocumentData>,
	'homepage',
	Lang
>;

type PageDocumentDataSlicesSlice =
	| TrustedBySlice
	| AssuranceWithImagesSlice
	| IndependentDesignSlice
	| PillarsSlice
	| HeroStatementSlice
	| ValuePropositionSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
	/**
	 * Title field in *Page*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField;

	/**
	 * Slice Zone field in *Page*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	slices: prismic.SliceZone<PageDocumentDataSlicesSlice>; /**
	 * Meta Title field in *Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: page.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: page.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *Page*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<PageDocumentData>,
	'page',
	Lang
>;

/**
 * Content for Site settings documents
 */
interface SiteSettingsDocumentData {
	/**
	 * Site logo field in *Site settings*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: site_settings.site_logo
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	site_logo: prismic.ImageField<never>;

	/**
	 * Contact link field in *Site settings*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: site_settings.contact_link
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	contact_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Site settings document from Prismic
 *
 * - **API ID**: `site_settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SiteSettingsDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<SiteSettingsDocumentData>,
	'site_settings',
	Lang
>;

/**
 * Item in *Social links → Socials*
 */
export interface SocialLinksDocumentDataSocialsItem {
	/**
	 * Social link field in *Social links → Socials*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: LinkedIn
	 * - **API ID Path**: social_links.socials[].social_link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	social_link: prismic.LinkField<
		string,
		string,
		unknown,
		prismic.FieldState,
		'linkedin' | 'instagram' | 'tiktok' | 'facebook' | 'email'
	>;
}

/**
 * Content for Social links documents
 */
interface SocialLinksDocumentData {
	/**
	 * Socials field in *Social links*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: social_links.socials[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	socials: prismic.GroupField<Simplify<SocialLinksDocumentDataSocialsItem>>;
}

/**
 * Social links document from Prismic
 *
 * - **API ID**: `social_links`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SocialLinksDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<SocialLinksDocumentData>,
	'social_links',
	Lang
>;

/**
 * Content for Submenu documents
 */
interface SubMenuDocumentData {
	/**
	 * Submenu item field in *Submenu*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: sub_menu.submenu_item
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	submenu_item: prismic.Repeatable<
		prismic.LinkField<string, string, unknown, prismic.FieldState, never>
	>;
}

/**
 * Submenu document from Prismic
 *
 * - **API ID**: `sub_menu`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SubMenuDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<SubMenuDocumentData>,
	'sub_menu',
	Lang
>;

type UnderConstructionPageDocumentDataSlicesSlice = ComingSoonSlice;

/**
 * Content for Under Construction Page documents
 */
interface UnderConstructionPageDocumentData {
	/**
	 * Slice Zone field in *Under Construction Page*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: under_construction_page.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	slices: prismic.SliceZone<UnderConstructionPageDocumentDataSlicesSlice>; /**
	 * Meta Title field in *Under Construction Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: under_construction_page.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *Under Construction Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: under_construction_page.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *Under Construction Page*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: under_construction_page.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * Under Construction Page document from Prismic
 *
 * - **API ID**: `under_construction_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type UnderConstructionPageDocument<Lang extends string = string> =
	prismic.PrismicDocumentWithoutUID<
		Simplify<UnderConstructionPageDocumentData>,
		'under_construction_page',
		Lang
	>;

export type AllDocumentTypes =
	| FooterDocument
	| HeaderDocument
	| HomepageDocument
	| PageDocument
	| SiteSettingsDocument
	| SocialLinksDocument
	| SubMenuDocument
	| UnderConstructionPageDocument;

/**
 * Item in *FloatingImages → Default → Primary → Images*
 */
export interface AssuranceWithImagesSliceDefaultPrimaryImagesItem {
	/**
	 * Image field in *FloatingImages → Default → Primary → Images*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: assurance_with_images.default.primary.images[].image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>;
}

/**
 * Primary content in *FloatingImages → Default → Primary*
 */
export interface AssuranceWithImagesSliceDefaultPrimary {
	/**
	 * Heading field in *FloatingImages → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Enter heading
	 * - **API ID Path**: assurance_with_images.default.primary.heading
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	heading: prismic.RichTextField;

	/**
	 * Body field in *FloatingImages → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Enter body text
	 * - **API ID Path**: assurance_with_images.default.primary.body
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	body: prismic.RichTextField;

	/**
	 * CTA Link field in *FloatingImages → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: assurance_with_images.default.primary.ctaLink
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	ctaLink: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

	/**
	 * Images field in *FloatingImages → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: assurance_with_images.default.primary.images[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	images: prismic.GroupField<Simplify<AssuranceWithImagesSliceDefaultPrimaryImagesItem>>;
}

/**
 * Default variation for FloatingImages Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AssuranceWithImagesSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<AssuranceWithImagesSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *FloatingImages*
 */
type AssuranceWithImagesSliceVariation = AssuranceWithImagesSliceDefault;

/**
 * FloatingImages Shared Slice
 *
 * - **API ID**: `assurance_with_images`
 * - **Description**: Section with heading, body text, CTA link, and multiple accompanying images
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AssuranceWithImagesSlice = prismic.SharedSlice<
	'assurance_with_images',
	AssuranceWithImagesSliceVariation
>;

/**
 * Item in *ComingSoon → Default → Primary → Tags*
 */
export interface ComingSoonSliceDefaultPrimaryTagsItem {
	/**
	 * Tag field in *ComingSoon → Default → Primary → Tags*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: coming_soon.default.primary.tags[].tag
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	tag: prismic.KeyTextField;
}

/**
 * Item in *ComingSoon → Default → Primary → Images*
 */
export interface ComingSoonSliceDefaultPrimaryImagesItem {
	/**
	 * Image field in *ComingSoon → Default → Primary → Images*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: coming_soon.default.primary.images[].image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>;
}

/**
 * Item in *ComingSoon → Default → Primary → Bottom texts*
 */
export interface ComingSoonSliceDefaultPrimaryBottomTextsItem {
	/**
	 * Bottom text field in *ComingSoon → Default → Primary → Bottom texts*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: coming_soon.default.primary.bottom_texts[].bottom_text
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	bottom_text: prismic.RichTextField;
}

/**
 * Primary content in *ComingSoon → Default → Primary*
 */
export interface ComingSoonSliceDefaultPrimary {
	/**
	 * Tags field in *ComingSoon → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: coming_soon.default.primary.tags[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	tags: prismic.GroupField<Simplify<ComingSoonSliceDefaultPrimaryTagsItem>>;

	/**
	 * Main Heading field in *ComingSoon → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: coming_soon.default.primary.heading
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	heading: prismic.RichTextField;

	/**
	 * Social Links field in *ComingSoon → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: coming_soon.default.primary.social_links
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	social_links: prismic.Repeatable<
		prismic.LinkField<string, string, unknown, prismic.FieldState, never>
	>;

	/**
	 * Images field in *ComingSoon → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: coming_soon.default.primary.images[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	images: prismic.GroupField<Simplify<ComingSoonSliceDefaultPrimaryImagesItem>>;

	/**
	 * Bottom texts field in *ComingSoon → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: coming_soon.default.primary.bottom_texts[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	bottom_texts: prismic.GroupField<Simplify<ComingSoonSliceDefaultPrimaryBottomTextsItem>>;
}

/**
 * Default variation for ComingSoon Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default coming soon variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ComingSoonSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<ComingSoonSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *ComingSoon*
 */
type ComingSoonSliceVariation = ComingSoonSliceDefault;

/**
 * ComingSoon Shared Slice
 *
 * - **API ID**: `coming_soon`
 * - **Description**: A coming soon landing page with tagline, main heading, and social links
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ComingSoonSlice = prismic.SharedSlice<'coming_soon', ComingSoonSliceVariation>;

/**
 * Item in *HeroHomepage → Default → Primary → Tags*
 */
export interface HeroStatementSliceDefaultPrimaryTagsItem {
	/**
	 * Tag field in *HeroHomepage → Default → Primary → Tags*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_statement.default.primary.tags[].tag
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	tag: prismic.KeyTextField;
}

/**
 * Item in *HeroHomepage → Default → Primary → Address lines*
 */
export interface HeroStatementSliceDefaultPrimaryAddressLinesItem {
	/**
	 * Line field in *HeroHomepage → Default → Primary → Address lines*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_statement.default.primary.address_lines[].line
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	line: prismic.KeyTextField;
}

/**
 * Item in *HeroHomepage → Default → Primary → Gallery*
 */
export interface HeroStatementSliceDefaultPrimaryGalleryItem {
	/**
	 * Image field in *HeroHomepage → Default → Primary → Gallery*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_statement.default.primary.gallery[].image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>;

	/**
	 * Video field in *HeroHomepage → Default → Primary → Gallery*
	 *
	 * - **Field Type**: Link to Media
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_statement.default.primary.gallery[].video
	 * - **Documentation**: https://prismic.io/docs/fields/link-to-media
	 */
	video: prismic.LinkToMediaField<prismic.FieldState, never>;
}

/**
 * Primary content in *HeroHomepage → Default → Primary*
 */
export interface HeroStatementSliceDefaultPrimary {
	/**
	 * Tags field in *HeroHomepage → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_statement.default.primary.tags[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	tags: prismic.GroupField<Simplify<HeroStatementSliceDefaultPrimaryTagsItem>>;

	/**
	 * Heading field in *HeroHomepage → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: e.g., We create trust in a digital world.
	 * - **API ID Path**: hero_statement.default.primary.heading
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	heading: prismic.RichTextField;

	/**
	 * Address lines field in *HeroHomepage → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_statement.default.primary.address_lines[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	address_lines: prismic.GroupField<Simplify<HeroStatementSliceDefaultPrimaryAddressLinesItem>>;

	/**
	 * Scroll Hint field in *HeroHomepage → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: e.g., (Scroll for more)
	 * - **API ID Path**: hero_statement.default.primary.scrollHint
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	scrollHint: prismic.KeyTextField;

	/**
	 * Gallery field in *HeroHomepage → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_statement.default.primary.gallery[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	gallery: prismic.GroupField<Simplify<HeroStatementSliceDefaultPrimaryGalleryItem>>;
}

/**
 * Default variation for HeroHomepage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default hero statement variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroStatementSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<HeroStatementSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *HeroHomepage*
 */
type HeroStatementSliceVariation = HeroStatementSliceDefault;

/**
 * HeroHomepage Shared Slice
 *
 * - **API ID**: `hero_statement`
 * - **Description**: Hero section with tagline, main heading, address, scroll hint, and image gallery
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroStatementSlice = prismic.SharedSlice<'hero_statement', HeroStatementSliceVariation>;

/**
 * Item in *StickyFeatures → Default → Primary → Features*
 */
export interface IndependentDesignSliceDefaultPrimaryFeaturesItem {
	/**
	 * Image field in *StickyFeatures → Default → Primary → Features*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: independent_design.default.primary.features[].image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>;

	/**
	 * Heading field in *StickyFeatures → Default → Primary → Features*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: independent_design.default.primary.features[].heading
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	heading: prismic.KeyTextField;

	/**
	 * Description field in *StickyFeatures → Default → Primary → Features*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: independent_design.default.primary.features[].description
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	description: prismic.RichTextField;

	/**
	 * CTA Link field in *StickyFeatures → Default → Primary → Features*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: independent_design.default.primary.features[].cta_link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	cta_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *StickyFeatures → Default → Primary*
 */
export interface IndependentDesignSliceDefaultPrimary {
	/**
	 * Features field in *StickyFeatures → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: independent_design.default.primary.features[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	features: prismic.GroupField<Simplify<IndependentDesignSliceDefaultPrimaryFeaturesItem>>;
}

/**
 * Default variation for StickyFeatures Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation with image on left and content on right
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type IndependentDesignSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<IndependentDesignSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *StickyFeatures*
 */
type IndependentDesignSliceVariation = IndependentDesignSliceDefault;

/**
 * StickyFeatures Shared Slice
 *
 * - **API ID**: `independent_design`
 * - **Description**: Hero section with badge, heading, description, image, and CTA button
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type IndependentDesignSlice = prismic.SharedSlice<
	'independent_design',
	IndependentDesignSliceVariation
>;

/**
 * Item in *FeatureCards → Default → Primary → Pillars*
 */
export interface PillarsSliceDefaultPrimaryPillarsItem {
	/**
	 * Title field in *FeatureCards → Default → Primary → Pillars*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: pillars.default.primary.pillars[].title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;

	/**
	 * Description field in *FeatureCards → Default → Primary → Pillars*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: pillars.default.primary.pillars[].description
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	description: prismic.RichTextField;

	/**
	 * Index field in *FeatureCards → Default → Primary → Pillars*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: pillars.default.primary.pillars[].index
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	index: prismic.KeyTextField;

	/**
	 * Background Color field in *FeatureCards → Default → Primary → Pillars*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: *None*
	 * - **API ID Path**: pillars.default.primary.pillars[].background_color
	 * - **Documentation**: https://prismic.io/docs/fields/color
	 */
	background_color: prismic.ColorField;

	/**
	 * Text color field in *FeatureCards → Default → Primary → Pillars*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: *None*
	 * - **API ID Path**: pillars.default.primary.pillars[].text_color
	 * - **Documentation**: https://prismic.io/docs/fields/color
	 */
	text_color: prismic.ColorField;

	/**
	 * Shape field in *FeatureCards → Default → Primary → Pillars*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: roundVerticalLines
	 * - **API ID Path**: pillars.default.primary.pillars[].shape
	 * - **Documentation**: https://prismic.io/docs/fields/select
	 */
	shape: prismic.SelectField<'roundVerticalLines' | 'roundWorldShape' | 'TriangleShape', 'filled'>;
}

/**
 * Item in *FeatureCards → Slider → Primary → Cards*
 */
export interface PillarsSliceSliderPrimaryCardsItem {
	/**
	 * Title field in *FeatureCards → Slider → Primary → Cards*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: pillars.slider.primary.cards[].title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;

	/**
	 * Description field in *FeatureCards → Slider → Primary → Cards*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: pillars.slider.primary.cards[].description
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	description: prismic.RichTextField;

	/**
	 * Background color field in *FeatureCards → Slider → Primary → Cards*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: Dark
	 * - **API ID Path**: pillars.slider.primary.cards[].background_color
	 * - **Documentation**: https://prismic.io/docs/fields/select
	 */
	background_color: prismic.SelectField<'Dark' | 'Aqua' | 'Clay', 'filled'>;

	/**
	 * Shape field in *FeatureCards → Slider → Primary → Cards*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: Cylinder
	 * - **API ID Path**: pillars.slider.primary.cards[].shape
	 * - **Documentation**: https://prismic.io/docs/fields/select
	 */
	shape: prismic.SelectField<'Cylinder' | 'Sphere' | 'Pyramid', 'filled'>;
}

/**
 * Primary content in *FeatureCards → Default → Primary*
 */
export interface PillarsSliceDefaultPrimary {
	/**
	 * Heading field in *FeatureCards → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: pillars.default.primary.heading
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	heading: prismic.RichTextField;

	/**
	 * Pillars field in *FeatureCards → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: pillars.default.primary.pillars[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	pillars: prismic.GroupField<Simplify<PillarsSliceDefaultPrimaryPillarsItem>>;
}

/**
 * Default variation for FeatureCards Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation of Pillars slice
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PillarsSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<PillarsSliceDefaultPrimary>,
	never
>;

/**
 * Primary content in *FeatureCards → Slider → Primary*
 */
export interface PillarsSliceSliderPrimary {
	/**
	 * Heading field in *FeatureCards → Slider → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: pillars.slider.primary.heading
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	heading: prismic.RichTextField;

	/**
	 * Cards field in *FeatureCards → Slider → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: pillars.slider.primary.cards[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	cards: prismic.GroupField<Simplify<PillarsSliceSliderPrimaryCardsItem>>;
}

/**
 * Slider variation for FeatureCards Slice
 *
 * - **API ID**: `slider`
 * - **Description**: Default variation of Pillars slice
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PillarsSliceSlider = prismic.SharedSliceVariation<
	'slider',
	Simplify<PillarsSliceSliderPrimary>,
	never
>;

/**
 * Slice variation for *FeatureCards*
 */
type PillarsSliceVariation = PillarsSliceDefault | PillarsSliceSlider;

/**
 * FeatureCards Shared Slice
 *
 * - **API ID**: `pillars`
 * - **Description**: Three pillar cards displaying company values/principles with title, description, and background color
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PillarsSlice = prismic.SharedSlice<'pillars', PillarsSliceVariation>;

/**
 * Item in *TrustedBy → Default → Primary → Logos*
 */
export interface TrustedBySliceDefaultPrimaryLogosItem {
	/**
	 * Logo Image field in *TrustedBy → Default → Primary → Logos*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: trusted_by.default.primary.logos[].logo_image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	logo_image: prismic.ImageField<never>;
}

/**
 * Primary content in *TrustedBy → Default → Primary*
 */
export interface TrustedBySliceDefaultPrimary {
	/**
	 * Logos field in *TrustedBy → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: trusted_by.default.primary.logos[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	logos: prismic.GroupField<Simplify<TrustedBySliceDefaultPrimaryLogosItem>>;

	/**
	 * Heading field in *TrustedBy → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Trusted by leading organisations
	 * - **API ID Path**: trusted_by.default.primary.heading
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	heading: prismic.KeyTextField;
}

/**
 * Default variation for TrustedBy Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation with heading and logo grid
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TrustedBySliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<TrustedBySliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *TrustedBy*
 */
type TrustedBySliceVariation = TrustedBySliceDefault;

/**
 * TrustedBy Shared Slice
 *
 * - **API ID**: `trusted_by`
 * - **Description**: A slice showcasing logos of trusted organizations in a grid layout
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TrustedBySlice = prismic.SharedSlice<'trusted_by', TrustedBySliceVariation>;

/**
 * Primary content in *RevealTypeWithCta → Default → Primary*
 */
export interface ValuePropositionSliceDefaultPrimary {
	/**
	 * Label field in *RevealTypeWithCta → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: e.g., Why Risk Boutique?
	 * - **API ID Path**: value_proposition.default.primary.label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	label: prismic.KeyTextField;

	/**
	 * Content field in *RevealTypeWithCta → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: We combine the agility of a boutique with...
	 * - **API ID Path**: value_proposition.default.primary.content
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	content: prismic.KeyTextField;

	/**
	 * CTA Link field in *RevealTypeWithCta → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: Talk to us
	 * - **API ID Path**: value_proposition.default.primary.cta_link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	cta_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for RevealTypeWithCta Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default value proposition variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ValuePropositionSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<ValuePropositionSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *RevealTypeWithCta*
 */
type ValuePropositionSliceVariation = ValuePropositionSliceDefault;

/**
 * RevealTypeWithCta Shared Slice
 *
 * - **API ID**: `value_proposition`
 * - **Description**: A value proposition section with label, heading, body text, and CTA link
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ValuePropositionSlice = prismic.SharedSlice<
	'value_proposition',
	ValuePropositionSliceVariation
>;

declare module '@prismicio/client' {
	interface CreateClient {
		(
			repositoryNameOrEndpoint: string,
			options?: prismic.ClientConfig
		): prismic.Client<AllDocumentTypes>;
	}

	interface CreateWriteClient {
		(
			repositoryNameOrEndpoint: string,
			options: prismic.WriteClientConfig
		): prismic.WriteClient<AllDocumentTypes>;
	}

	interface CreateMigration {
		(): prismic.Migration<AllDocumentTypes>;
	}

	namespace Content {
		export type {
			FooterDocument,
			FooterDocumentData,
			HeaderDocument,
			HeaderDocumentData,
			HeaderDocumentDataMenuItemsItem,
			HomepageDocument,
			HomepageDocumentData,
			HomepageDocumentDataSlicesSlice,
			PageDocument,
			PageDocumentData,
			PageDocumentDataSlicesSlice,
			SiteSettingsDocument,
			SiteSettingsDocumentData,
			SocialLinksDocument,
			SocialLinksDocumentData,
			SocialLinksDocumentDataSocialsItem,
			SubMenuDocument,
			SubMenuDocumentData,
			UnderConstructionPageDocument,
			UnderConstructionPageDocumentData,
			UnderConstructionPageDocumentDataSlicesSlice,
			AllDocumentTypes,
			AssuranceWithImagesSlice,
			AssuranceWithImagesSliceDefaultPrimaryImagesItem,
			AssuranceWithImagesSliceDefaultPrimary,
			AssuranceWithImagesSliceVariation,
			AssuranceWithImagesSliceDefault,
			ComingSoonSlice,
			ComingSoonSliceDefaultPrimaryTagsItem,
			ComingSoonSliceDefaultPrimaryImagesItem,
			ComingSoonSliceDefaultPrimaryBottomTextsItem,
			ComingSoonSliceDefaultPrimary,
			ComingSoonSliceVariation,
			ComingSoonSliceDefault,
			HeroStatementSlice,
			HeroStatementSliceDefaultPrimaryTagsItem,
			HeroStatementSliceDefaultPrimaryAddressLinesItem,
			HeroStatementSliceDefaultPrimaryGalleryItem,
			HeroStatementSliceDefaultPrimary,
			HeroStatementSliceVariation,
			HeroStatementSliceDefault,
			IndependentDesignSlice,
			IndependentDesignSliceDefaultPrimaryFeaturesItem,
			IndependentDesignSliceDefaultPrimary,
			IndependentDesignSliceVariation,
			IndependentDesignSliceDefault,
			PillarsSlice,
			PillarsSliceDefaultPrimaryPillarsItem,
			PillarsSliceDefaultPrimary,
			PillarsSliceSliderPrimaryCardsItem,
			PillarsSliceSliderPrimary,
			PillarsSliceVariation,
			PillarsSliceDefault,
			PillarsSliceSlider,
			TrustedBySlice,
			TrustedBySliceDefaultPrimaryLogosItem,
			TrustedBySliceDefaultPrimary,
			TrustedBySliceVariation,
			TrustedBySliceDefault,
			ValuePropositionSlice,
			ValuePropositionSliceDefaultPrimary,
			ValuePropositionSliceVariation,
			ValuePropositionSliceDefault
		};
	}
}
